
main:
  push:
    - runner:
        tags: cnb:arch:amd64
      services:
        - docker
      stages:
        - name: docker login
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: docker build
          script: ./build.sh
        - name: docker push
          script: ./push.sh
        - name: resolve
          type: cnb:resolve
          options:
            key: build-amd64 
          
    - runner:
        tags: cnb:arch:arm64:v8
      services:
        - docker
      stages:
        - name: docker login
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: docker build
          script: ./build.sh
        - name: docker push
          script: ./push.sh
        - name: resolve
          type: cnb:resolve
          options:
            key: build-arm64

    - services:
        - docker
      env:
        IMAGE_TAG: docker.cnb.cool/polaris-tian/wvp-docker/polaris-redis:latest
        REDIS_IMAGE_NAME: ${CNB_REPO_NAME}/polaris-redis
      stages:
        - name: await the amd64
          type: cnb:await
          options:
            key: build-amd64
        - name: await the arm64
          type: cnb:await
          options:
            key: build-arm64
        - name: manifest
          image: cnbcool/manifest
          settings:
            target: ${IMAGE_TAG}
            template: ${IMAGE_TAG}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        - name: remove tag
          type: artifact:remove-tag
          options:
            name: ${REDIS_IMAGE_NAME}
            tags:
              - latest-linux-amd64
              - latest-linux-arm64
            type: docker