version: '3.3'
services:
  polaris-redis:
    image: docker.cnb.cool/polaris-tian/wvp-docker/polaris-redis:latest
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - 6390:6379
    volumes:
      - ./volumes/redis/data/:/data
    environment:
      TZ: "Asia/Shanghai"
      REDIS_PASSWORD: ${REDIS_PASSWORD:-Data@123456}
    command: sh -c "redis-server /usr/local/redis.conf --requirepass $${REDIS_PASSWORD}"
    networks:
      - wvp-net

  polaris-mysql:
    image: docker.cnb.cool/polaris-tian/wvp-docker/polaris-mysql:latest
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/3306" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_DATABASE: wvp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: polaris
      MYSQL_PASSWORD: Data@123
      TZ: Asia/Shanghai
    ports:
      - 3310:3306
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./logs/mysql:/logs
      - ./volumes/mysql/data:/var/lib/mysql  
    command: [
          'mysqld',
          '--default-authentication-plugin=mysql_native_password',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_general_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    networks:
      - wvp-net

  polaris-media:
    image: docker.cnb.cool/polaris-tian/wvp-docker/polaris-media:latest
    network_mode: "host"
    restart: always
    ports:
      - "10935:10935"
      - "5540:5540"
      - "6080:6080"
      - "10000:10000/tcp"
      - "10000:10000/udp"
      - "8000:8000/tcp"
      - "8000:8000/udp"
      - "9000:9000"
    volumes:
      - ./volumes/video:/opt/media/www/record/
      - ./volumes/media/assist:/opt/media/assist/
      - ./logs/media:/opt/media/log/
      - ./media/config.ini:/opt/media/conf/config.ini

  polaris-wvp:
    image: docker.cnb.cool/polaris-tian/wvp-docker/polaris-wvp:latest
    network_mode: "host"
    restart: always
    ports:
      - "18978:18978"
      - "18081:18081"
      - "8116:8116/udp"
      - "8116:8116/tcp"
      - "30000:30500"
      - "50502:50506"
      - "30000:30500/udp"
      - "50502:50506/udp"
    depends_on:
      - polaris-redis
      - polaris-mysql
      - polaris-media
    volumes:
      - ./wvp/wvp:/opt/wvp/conf/
      - ./wvp/assist/conf:/opt/assist/conf/
      - ./logs/wvp:/opt/wvp/logs/
      - ./volumes/wvp/assist:/opt/media/assist/
    environment:
      # 本机的IP(物理机IP)
      SIP_HOST: 172.18.61.2
      STREAM_HOST: 172.18.61.2
      SDP_HOST: 172.18.61.2
      HOOK_HOST: 172.18.61.2
      ZLM_HOST: 127.0.0.1
      ZLM_PORT: 6080
      ZLM_SERCERT: su6TiedN2rVAmBbIDX0aa0QTiBJLBdcf
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6390
      REDIS_PASSWORD: ${REDIS_PASSWORD:-Data@123456}
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3310
      MYSQL_DATABASE: wvp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      # 前端跨域配置，nginx容器所在物理机IP
      NGINX_HOST: http://172.18.61.2:8080

  polaris-nginx:
    image: docker.cnb.cool/polaris-tian/wvp-docker/polaris-nginx:latest
    network_mode: "host"
    ports:
      - "8080:8080"
    depends_on:
      - polaris-wvp
    environment:
      - WVP_HOST=172.18.61.2
      - WVP_PORT=18978
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
      - ./nginx/config.js:/opt/dist/static/js/config.js

networks:
  wvp-net:
    driver: bridge