version: '3'
services:
  ylcx-redis:
    image: polaris-tian-docker.pkg.coding.net/qt/polaris/ylcx-redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/conf/redis.conf:/opt/ylcx/redis/redis.conf
      - ./redis/data/:/data
    environment:
      TZ: "Asia/Shanghai"
    command: redis-server /opt/ylcx/redis/redis.conf --appendonly yes
  
  ylcx-mysql:
    image: polaris-tian-docker.pkg.coding.net/qt/polaris/ylcx-mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: wvp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ylcx
      MYSQL_PASSWORD: ylcx
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./logs/mysql:/logs
      - ./mysql/data:/var/lib/mysql  
    command: [
          'mysqld',
          '--default-authentication-plugin=mysql_native_password',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_general_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
  ylcx-media:
    image: polaris-tian-docker.pkg.coding.net/qt/polaris/ylcx-media:latest
    restart: always
    ports:
      - "10935:10935"
      - "5540:5540"
      - "6080:6080"
    volumes:
      - ./video:/opt/media/www/record/
      - ./logs/media:/opt/media/log/
  ylcx-wvp:
    image: polaris-tian-docker.pkg.coding.net/qt/polaris/ylcx-wvp:latest
    restart: always
    ports:
      - "18978:18978"
      - "8116:8116/udp"
      - "8116:8116/tcp"
    depends_on:
      - ylcx-redis
      - ylcx-mysql
      - ylcx-media
    links:
      - ylcx-redis
      - ylcx-mysql
      - ylcx-media
    volumes:
      - ./wvp/wvp/:/opt/ylcx/wvp/
      - ./logs/wvp:/opt/wvp/logs/
    environment:
      TZ: "Asia/Shanghai"
      # 本机的IP
      SIP_HOST: 127.0.0.1
      STREAM_HOST: 127.0.0.1
      ZLM_HOST: ylcx-media
      ZLM_PORT: 6080
      ZLM_SERCERT: su6TiedN2rVAmBbIDX0aa0QTiBJLBdcf
      REDIS_HOST: ylcx-redis
      REDIS_PORT: 6379
      DATABASE_HOST: ylcx-mysql
      DATABASE_PORT: 3306
      DATABASE_USER: ylcx
      DATABASE_PASSWORD: ylcx
      # 前端跨域配置，nginx容器所在物理机IP
      NGINX_HOST: http://127.0.0.1:8080

  ylcx-nginx:
    image: polaris-tian-docker.pkg.coding.net/qt/polaris/ylcx-nginx:latest
    ports:
      - "8080:8080"
    depends_on:
      - ylcx-wvp
    links:
      - ylcx-wvp  
    environment:
      WVP_HOST: ylcx-wvp
      WVP_PORT: 18978
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx