name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # - name: Build Docker Image
      #   working-directory:  ${{ github.workspace }}
      #   run: chmod +x ./build.sh && ./build.sh


      - name: Push Docker Image
        working-directory:  ${{ github.workspace }}
        env:
          CODING_USER: ${{ env.CODING_USER }}
          CODING_PASSWD: ${{ env.CODING_PASSWD }}
        run: docker login -u "$CODING_USER" -p "$CODING_PASSWD" polaris-tian-docker.pkg.coding.net && chmod +x ./push.sh && ./push.sh

    
    
