name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker Image
        working-directory:  ${{ github.workspace }}
        run: chmod +x ./build.sh && ./build.sh


      - name: Push Docker Image
        working-directory:  ${{ github.workspace }}
        run: docker login -u ${{ env.CODING_USERNAME }} -p ${{ env.CODING_PASSWD }} polaris-tian-docker.pkg.coding.net && chmod +x ./push.sh && ./push.sh

    
    
